import { GeoPoint } from './location.service';

export interface FoodCatalogItem {
  id: string;
  image: string;
  alt: string;
  title: string;
  description: string;
  pickupLocation: GeoPoint;
  location: string;
  timeOperational: string;
}

export const foodCatalog: FoodCatalogItem[] = [
  {
    id: '1',
    image: '/images/food-expires.png',
    alt: 'bakery-leftover',
    title: 'Artisan Bakery Batch',
    description:
      "6 loaves of freshly baked whole grain sourdough from today's unsold bakery stock. Still soft and perfect for shelters or community kitchens.",
    pickupLocation: { latitude: -8.6705, longitude: 115.2126 },
    location: 'Renon, Denpasar',
    timeOperational: '21:20 WIB - 22:40 WIB',
  },
  {
    id: '2',
    image: '/images/food-expires.png',
    alt: 'prepared-meals',
    title: 'Community Meal Package',
    description: 'Prepared meal packs from a catering partner, ready for scheduled evening pickup.',
    pickupLocation: { latitude: -7.2575, longitude: 112.7521 },
    location: 'Tegalsari, Surabaya',
    timeOperational: '18:30 WIB - 20:00 WIB',
  },
  {
    id: '3',
    image: '/images/food-1.png',
    alt: 'vegetable-box',
    title: 'Organic Veggie Basket',
    description: 'Organic greens and root vegetables grouped for family-sized collection.',
    pickupLocation: { latitude: -6.9147, longitude: 107.6098 },
    location: 'Coblong, Bandung',
    timeOperational: '17:00 WIB - 19:30 WIB',
  },
  {
    id: '4',
    image: '/images/food-2.png',
    alt: 'fruit-box',
    title: 'Surplus Fruit Collection',
    description: 'Sorted fruit boxes from a fresh market vendor with same-day pickup priority.',
    pickupLocation: { latitude: -6.2088, longitude: 106.8456 },
    location: 'Menteng, Jakarta Pusat',
    timeOperational: '19:00 WIB - 21:00 WIB',
  },
  {
    id: '5',
    image: '/images/food-3.png',
    alt: 'rice-meals',
    title: 'Prepared Rice Meals',
    description: 'Ready-to-share rice meal packs portioned from lunch service surplus.',
    pickupLocation: { latitude: -7.7956, longitude: 110.3695 },
    location: 'Gondokusuman, Yogyakarta',
    timeOperational: '16:30 WIB - 18:30 WIB',
  },
  {
    id: '6',
    image: '/images/food-4.png',
    alt: 'seafood-pack',
    title: 'Fresh Seafood Package',
    description: 'Chilled seafood packs that need quick collection to preserve quality.',
    pickupLocation: { latitude: 1.4748, longitude: 124.8421 },
    location: 'Wenang, Manado',
    timeOperational: '14:00 WITA - 16:00 WITA',
  },
  {
    id: '7',
    image: '/images/food-5.png',
    alt: 'grocery-essentials',
    title: 'Daily Grocery Essentials',
    description: 'A mixed essentials kit with produce, eggs, and pantry basics.',
    pickupLocation: { latitude: -5.1477, longitude: 119.4327 },
    location: 'Ujung Pandang, Makassar',
    timeOperational: '18:00 WITA - 20:30 WITA',
  },
  {
    id: '8',
    image: '/images/food-6.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '9',
    image: '/images/food-7.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '10',
    image: '/images/food-8.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '11',
    image: '/images/food-9.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '12',
    image: '/images/food-10.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '13',
    image: '/images/food-11.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '14',
    image: '/images/food-12.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '15',
    image: '/images/food-13.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '16',
    image: '/images/food-14.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '17',
    image: '/images/food-15.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
  {
    id: '18',
    image: '/images/food-16.png',
    alt: 'bread-drop',
    title: 'Fresh Bread Night Pickup',
    description: 'A late pickup bread batch suitable for direct neighborhood sharing.',
    pickupLocation: { latitude: -2.5337, longitude: 140.7181 },
    location: 'Abepura, Jayapura',
    timeOperational: '19:30 WIT - 21:00 WIT',
  },
];

export const getFoodById = (foodId: string | null | undefined): FoodCatalogItem | undefined =>
  foodCatalog.find((food) => food.id === foodId);
